# Generated by Django 4.2.10 on 2024-02-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earthquake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('magnitude', models.FloatField()),
                ('place', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('detail', models.URLField()),
                ('status', models.CharField(max_length=20)),
                ('tsunami', models.BooleanField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
